version: '3'

services:
    api:
        build: ./src
        container_name: tstm-api
        command: npm run start
        restart: unless-stopped
        environment: 
            - API_PORT=3000
            - DB_HOST=localhost
            - DB_PORT=5432
        depends_on: 
            - db
        networks: 
            - tstm

    db:
        container_name: tstm-db
        image: postgres:13.0-alpine
        networks: 
            - tstm
