version: '3'

services:
  api:
    build: ./api
    container_name: tstm-api
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment: 
      - NODE_ENV=production
    depends_on:
      - api_db
    networks:
      - tstm

  api_db:
    container_name: tstm-db
    image: postgres
    env_file: 
      - ./db/postgresql.env
    volumes: 
      - ./db/data/postgres:/var/lib/postgresql/data
    networks:
      - tstm
    # ports: 
    #   - "5433:5433"

networks: 
  tstm:
    driver: bridge
